apiVersion: v1
kind: Pod
metadata:
  name: python-logger
  labels:
    app: python-logger
spec:
  containers:
    - name: python-logger
      image: dockeritc778/python-logger:latest
      imagePullPolicy: Always